sounds:
  # - name: card_deal
  #   path: Game/Assets/Sounds/card_deal.wav

  # - name: card_pickup
  #   path: Game/Assets/Sounds/card_pickup.wav

  # - name: card_release
  #   path: Game/Assets/Sounds/card_release.wav
 