cursors:
  # - name: arrow
  #   mode: 0
  #   image: Game/Assets/Cursors/BACursor.png
  #   hotspot: [ 0.0, 0.0 ]
  
  # - name: grabbing
  #   mode: 1
  #   image: assets/cursors/cursor_hand_closed.png
  #   hotspot: [ 0.0, 0.0 ]
